---
instance_groups:
  - name: web
    jobs:
    - name: atc
      properties:
        github_auth: (( prune ))
        generic_auth: (( prune ))
        basic_auth_username: (( prune ))
        basic_auth_password: (( prune ))
        uaa_auth:
          cf_spaces:     (( grab params.cf_spaces ))
          client_id:     (( vault meta.vault "/oauth:provider_key" ))
          client_secret: (( vault meta.vault "/oauth:provider_secret" ))
  
          cf_api_url:   (( grab params.cf_api_url ))
          auth_url:  (( grab params.uaa_auth_url ))
          token_url: (( grab params.uaa_token_url ))
          cf_ca_cert: (( vault params.cf_ca_cert_vault_path ))
