---
params:
  github_host: (( param "Please provide the domain to your GitHub Enterprise installation"))

meta:
  jobs:
    atc:
      properties:
        github_auth:
          #ca_cert: "SPECIFY THIS IF YOU NEED IT"
          host:     (( grab params.github_host))
