---
params:
  authz_allowed_orgs: (( param "Please provide a list of org/teams/users authorized for using Concourse" ))

instance_groups:
  - name: web
    jobs:
    - name: atc
      properties:
        uaa_auth: (( prune ))
        generic_auth: (( prune ))
        basic_auth_username: (( prune ))
        basic_auth_password: (( prune ))
        github_auth:
          authorize:
          - organization: (( grab params.authz_allowed_orgs ))
            teams: all
          client_id:     (( vault meta.vault "/oauth:provider_key" ))
          client_secret: (( vault meta.vault "/oauth:provider_secret" ))
