---
params:
  authz_allowed_orgs: (( param "Please provide the name of the organization authorized for using Concourse" ))

meta:
  default:
    github_authz:
      - organization: (( grab params.authz_allowed_orgs ))
        teams:        all

meta:
  jobs:
    web:
      properties:
        main_team:
          auth:
            github:
              orgs: [(( grab params.authz_allowed_orgs || params.github.orgs ))]

        github_auth:
          client_id:     (( vault meta.vault "/oauth:provider_key" ))
          client_secret: (( vault meta.vault "/oauth:provider_secret" ))
