---
meta:
  releases:
    concourse:
      name:    concourse
      version: 5.0.1
      sha1:    122b2775423cbed5dfc147ed771c864940a19bb3
      url:     https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=5.0.1
    slack-notifications:
      name:    slack-notification-resource
      version: 9
      sha1:    a64c65d1f23ea089746e698f29dbe522dd716c1b
      url:     https://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
    bpm:
      name:    bpm
      version: 1.0.3
      sha1:    2875a69cae225fa97fe3faae1e9fbacff61e2dc5
      url:     https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.3
    shout:
      name:    shout
      version: 0.1.0
      sha1:    73c5c0161730a655c03f5a6ceb1c8b2e33403874
      url:     https://github.com/jhunt/shout-boshrelease/releases/download/v0.1.0/shout-0.1.0.tar.gz
    postgres:
      name:    postgres
      version: 31
      sha1:    bbe4151f4000f349c2ffaf72412aac9cc0a3c741
      url:     https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=31
    locker:
      name:    locker
      version: 0.2.1
      sha1:    ccfcc48d63555a3733c3594d9429a5c1875a9dd2
      url:     https://github.com/cloudfoundry-community/locker-boshrelease/releases/download/v0.2.1/locker-0.2.1.tgz  
    haproxy:
      name:    haproxy
      version: 8.4.2
      sha1:    8ebad4c8e57fac2fba9da07536f61efe8141be6f
      url:     https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=8.4.2
  


