---
meta:
  kit:     concourse
  release: Concourse Genesis Kit
  target:  buf
  url:     https://10.200.131.2.netip.cc

  initial_version: 1.3.0

  bosh:
    uri:      ((bosh.uri))
    username: ((bosh.username))
    password: ((bosh.password))
    cacert:   ((bosh.ca))

  vault:
    url:       https://10.128.4.4
    role_id:   ((vault.role_id))
    secret_id: ((vault.secret_id))

  aws:
    access_key: ((aws.access_key_id))
    secret_key: ((aws.secret_access_key))

  github:
    owner:        genesis-community
    repo:         concourse-genesis-kit
    branch:       master
    private_key:  ((github.private_key))
    access_token: ((github.access_token))

  slack:
    webhook:  ((slack.webhook))
    channel:  '#botspam'
    username: starkandwayne-ci
    icon:     https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
