---
params:
  ssl_pem:           (( vault meta.vault "/ssl/server:combined" ))
  external_domain:   (( param "Please specify the IP/DNS users will use to connect to Concourse" ))
  external_url:      (( concat "https://" params.external_domain ))
  concourse_network: concourse
  concourse_vm_type: small
  concourse_disk_type: concourse
  stemcell_os: ubuntu-trusty
  stemcell_version: latest

  availability_zones:
  - z1
  - z2
  - z3
