---
meta:
  vault: (( concat "secret/" params.vault ))

instance_groups:
  - name: haproxy
    instances: 1
    azs: (( grab params.availability_zones ))
    stemcell: default
    vm_type: (( grab params.concourse_vm_type ))
    networks:
    - name: (( grab params.concourse_network ))
      static_ips: (( static_ips 0 ))
    jobs:
      - release: haproxy
        name: haproxy
        properties:
          ha_proxy:
            backend_port: 8080
            backend_servers: (( grab instance_groups.web.networks.0.static_ips ))
            ssl_pem: (( grab params.ssl_pem ))
            https_redirect_all: true

  - name: web
    instances: 1
    azs: (( grab params.availability_zones ))
    stemcell: default
    vm_type: (( grab params.concourse_vm_type ))
    networks:
    - name: (( grab params.concourse_network ))
      static_ips: (( static_ips 1, 2 ))
    jobs:
      - release: concourse
        name: tsa
        properties:
          host_key: (( vault meta.vault "/tsa/host_key:private" ))
          host_public_key: (( vault meta.vault "/tsa/host_key:public" ))
          authorized_keys:
          - (( vault meta.vault "/tsa/worker_key:public" ))
          authorize_generated_worker_key: false
      - release: concourse
        name: atc
        properties:
          bind_port: 8080
          publicly_viewable: true
          postgresql_database: atc
          basic_auth_username: concourse
          basic_auth_password: (( vault meta.vault "/webui:password" ))
          external_url: (( grab params.external_url ))

  - name: db
    instances: 1
    azs: (( grab params.availability_zones ))
    stemcell: default
    vm_type: (( grab params.concourse_vm_type ))
    networks:
    - name: (( grab params.concourse_network ))
      static_ips: (( static_ips 3 ))
    persistent_disk_pool: (( grab params.concourse_disk_type ))
    jobs:
      - release: concourse
        name: postgresql
        properties:
          databases:
            - name: atc
              role: atc
              password: (( vault meta.vault "/database/atc:password" ))
      - name: locker
        release: locker
        properties:
          locker:
            user: locker
            password: (( vault meta.vault "/locker/api:password" ))
            ssl_cert: (( vault meta.vault "/locker/server:certificate" ))
            ssl_key: (( vault meta.vault "/locker/server:key" ))

  - name: worker
    instances: 3
    azs: (( grab params.availability_zones ))
    stemcell: default
    vm_type: (( grab params.concourse_vm_type ))
    networks:
    - name: (( grab params.concourse_network ))
    update:
      serial: true
      max_in_flight: (( grab instance_groups.worker.instances ))
    jobs:
      - release: concourse
        name: groundcrew
        properties:
          tsa:
            private_key: (( vault meta.vault "/tsa/worker_key:private" ))
            host_public_key: (( vault meta.vault "/tsa/host_key:public" ))
      - release: concourse
        name: baggageclaim
        properties: {}
      - release: garden-runc
        name: garden
        properties:
          garden:
            listen_network: tcp
            listen_address: 0.0.0.0:7777
            enable_graph_cleanup: true


update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: false

releases:
- name: concourse
  sha1: 65a974b3831bb9908661a5ffffbe456e10185149
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.5.0
  version: 3.5.0
- name: locker
  sha1: ccfcc48d63555a3733c3594d9429a5c1875a9dd2
  url: https://github.com/cloudfoundry-community/locker-boshrelease/releases/download/v0.2.1/locker-0.2.1.tgz
  version: 0.2.1
- name: haproxy
  sha1: 01ff0f16c9f55eb6f56d5735772934de31b2ceb2
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=8.4.0
  version: 8.4.0
- name: garden-runc
  sha1: 58fbc64aff303e6d76899441241dd5dacef50cb7
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.6.0
  version: 1.6.0
- name: slack-notification-resource
  sha1: a64c65d1f23ea089746e698f29dbe522dd716c1b
  url: https://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
  version: 9

stemcells:
- alias: default
  os: (( grab params.stemcell_os ))
  version: (( grab params.stemcell_version ))
