---
params:
  authz_allowed_orgs: (( param "Please provide a list of org/teams/users authorized for using Concourse" ))

  github_api_url:       (( param "Please provide the URL to your GitHub Enterprise API (requires trailing slash" ))
  github_token_url:     (( param "Please provide the URL to your GitHub Enterprise token endpoint" ))
  github_auth_url:      (( param "Please provide the URL to your GitHub Enterprise OAuth endpoint" ))
